// Language translations
const translations = {
    en: {
        // Header
        logo: "Company Name",
        home: "Home",
        about: "About",
        services: "Services",
        products: "Products",
        contact: "Contact",
        
        // Index page - Hero
        heroTitle: "Welcome to Company Name",
        heroSubtitle: "Innovative solutions for your business success. We transform ideas into reality with cutting-edge technology.",
        exploreServices: "Explore Our Services",
        getInTouch: "Get in Touch",
        
        // Index page - Sections
        aboutTitle: "About Us",
        aboutText: "We are a leading technology company dedicated to delivering innovative solutions that drive business growth. With over 10 years of experience and a team of 50+ specialists, we help businesses transform through technology.",
        learnMore: "Learn More",
        
        servicesTitle: "Our Services",
        servicesText: "We offer comprehensive technology solutions tailored to your business needs.",
        viewAllServices: "View All Services →",
        
        productsTitle: "Our Products",
        productsText: "Innovative software products designed for business excellence.",
        prod1Preview: "AI-powered analytics platform for data-driven decisions.",
        prod2Preview: "Secure cloud platform for corporate data management.",
        prod3Preview: "Project management system with collaboration tools.",
        viewAllProducts: "View All Products →",
        
        // References Section
        referencesTitle: "What Our Clients Say",
        referencesText: "Hear from businesses we've helped succeed with our technology solutions.",
        testimonial1Text: "Working with Company Name transformed our business. Their web platform increased our sales by 150% in the first year.",
        testimonial1Name: "Ivan Petrov",
        testimonial1Position: "CEO, TechStart Bulgaria",
        testimonial2Text: "Exceptional service and outstanding results. The mobile app they developed exceeded all our expectations.",
        testimonial2Name: "Maria Ivanova",
        testimonial2Position: "Director, Retail Solutions",
        testimonial3Text: "Professional team with deep technical expertise. They delivered our cloud migration project on time and within budget.",
        testimonial3Name: "Georgi Dimitrov",
        testimonial3Position: "IT Manager, Finance Corp",
        
        contactTitle: "Ready to Start Your Project?",
        contactText: "Get in touch with our team to discuss how we can help transform your business with innovative technology solutions.",
        contactButton: "Contact Us Now",
        
        // Footer
        quickLinks: "Quick Links",
        support: "Support",
        connect: "Connect",
        homeLink: "Home",
        aboutUs: "About Us",
        faq: "FAQ",
        helpCenter: "Help Center",
        contactUs: "Contact Us",
        privacyPolicy: "Privacy Policy",
        facebook: "Facebook",
        twitter: "Twitter",
        linkedin: "LinkedIn",
        instagram: "Instagram",
        copyright: "All rights reserved.",
        terms: "Terms of Service",
        
        // About page
        aboutHeroTitle: "About Us",
        aboutHeroSubtitle: "Innovation, quality and dedication – that's our mission",
        ourStoryTitle: "Our Story",
        ourStoryP1: "Company Name was founded in 2010 with a vision to transform the way businesses use technology. We started as a small team of enthusiasts united by a shared passion for innovation and quality solutions.",
        ourStoryP2: "Over the years, we have grown into a leading company in the field of business technology, serving hundreds of clients in Bulgaria and abroad. Our success lies in our dedication to clients and continuous improvement.",
        ourStoryP3: "Today we are proud of a team of over 50 professionals, modern offices and a portfolio of successfully completed projects in various industries - from finance and healthcare to trade and manufacturing.",
        achievementsTitle: "Our Achievements",
        projects: "Projects",
        clients: "Clients",
        yearsExp: "Years Experience",
        specialists: "Specialists",
        ourTeamTitle: "Our Team",
        ceo: "Chief Executive Officer",
        cto: "Chief Technology Officer",
        devManager: "Development Manager",
        designDirector: "Design Director",
        ceoBio: "15 years of experience in the IT industry. A visionary focused on innovation.",
        ctoBio: "Expert in software architecture and technology project management.",
        devManagerBio: "Passionate developer and leader of a team of talented programmers.",
        designDirectorBio: "Creative mind with a focus on user experience and visual communication.",
        ourValuesTitle: "Our Values",
        qualityTitle: "Quality",
        qualityDesc: "We strive for the highest standards in every project and interaction with clients.",
        innovationTitle: "Innovation",
        innovationDesc: "We constantly seek new technologies and approaches to solving business challenges.",
        partnershipTitle: "Partnership",
        partnershipDesc: "We build long-term relationships based on trust and mutual benefit.",
        commitmentTitle: "Commitment",
        commitmentDesc: "We are dedicated to the success of our clients and their growth.",
        
        // Services page
        servicesHeroTitle: "Our Services",
        servicesHeroSubtitle: "Comprehensive solutions tailored to your business needs. We deliver excellence through innovation and expertise.",
        whatWeOffer: "What We Offer",
        bizConsultTitle: "Business Consulting",
        bizConsultDesc: "Strategic planning and advisory services to help your business grow and succeed in competitive markets.",
        webDevTitle: "Web Development",
        webDevDesc: "Custom web applications and websites built with modern technologies to enhance your digital presence.",
        mobileAppTitle: "Mobile Applications",
        mobileAppDesc: "Native and cross-platform mobile apps designed to engage your customers on iOS and Android devices.",
        uiUxTitle: "UI/UX Design",
        uiUxDesc: "User-centered design solutions that create intuitive and visually appealing digital experiences.",
        cloudTitle: "Cloud Solutions",
        cloudDesc: "Scalable cloud infrastructure and migration services to modernize your IT operations.",
        dataAnalyticsTitle: "Data Analytics",
        dataAnalyticsDesc: "Transform your data into actionable insights with advanced analytics and business intelligence tools.",
        cybersecurityTitle: "Cybersecurity",
        cybersecurityDesc: "Comprehensive security solutions to protect your business from cyber threats and vulnerabilities.",
        aiMlTitle: "AI & Machine Learning",
        aiMlDesc: "Leverage artificial intelligence and machine learning to automate processes and gain competitive advantages.",
        learnMore: "Learn More",
        whyChooseUs: "Why Choose Us",
        provenExpertiseTitle: "🏆 Proven Expertise",
        provenExpertiseDesc: "Over 10 years of experience delivering successful projects across various industries.",
        fastDeliveryTitle: "⚡ Fast Delivery",
        fastDeliveryDesc: "Agile methodologies ensure rapid development and deployment without compromising quality.",
        qualityAssuranceTitle: "💎 Quality Assurance",
        qualityAssuranceDesc: "Rigorous testing and quality control processes guarantee reliable and bug-free solutions.",
        dedicatedSupportTitle: "🤝 Dedicated Support",
        dedicatedSupportDesc: "24/7 customer support and maintenance to keep your systems running smoothly.",
        ctaTitle: "Ready to Get Started?",
        ctaSubtitle: "Let's discuss how our services can help transform your business. Contact us today for a free consultation.",
        requestQuote: "Request a Quote",
        
        // Products page
        productsHeroTitle: "Our Products",
        productsHeroSubtitle: "Innovative solutions developed with cutting-edge technologies for your business success",
        discoverOurRange: "Discover Our Product Range",
        fromStartupsTo: "From small startups to large corporations - we have the perfect solution for every business",
        badgeNew: "New",
        badgePopular: "Popular",
        badgeBestseller: "Bestseller",
        prod1Category: "Business Analytics",
        prod1Title: "Business Analytics Pro",
        prod1Desc: "Powerful business analysis platform with AI-based forecasting and real-time data visualization.",
        prod1Feature1: "Interactive dashboards",
        prod1Feature2: "AI predictive analysis",
        prod1Feature3: "Export to Excel, PDF",
        prod1Feature4: "ERP system integration",
        prod2Category: "Cloud Solutions",
        prod2Title: "CloudSync Enterprise",
        prod2Desc: "Secure cloud platform for storing, syncing and sharing corporate data.",
        prod2Feature1: "Unlimited storage",
        prod2Feature2: "256-bit encryption",
        prod2Feature3: "Automatic backup",
        prod2Feature4: "24/7 technical support",
        prod3Category: "Project Management",
        prod3Title: "TeamWork Manager",
        prod3Desc: "Intuitive project and team management system with built-in communication tools.",
        prod3Feature1: "Kanban and Gantt charts",
        prod3Feature2: "Video conferencing",
        prod3Feature3: "Time tracking",
        prod3Feature4: "Mobile app",
        prod4Category: "Cybersecurity",
        prod4Title: "SecureGuard Pro",
        prod4Desc: "Comprehensive protection against cyber threats with AI anomaly detection and automatic defense.",
        prod4Feature1: "Real-time protection",
        prod4Feature2: "Firewall and antivirus",
        prod4Feature3: "Traffic monitoring",
        prod4Feature4: "Automatic updates",
        prod5Category: "Artificial Intelligence",
        prod5Title: "AI Assistant Plus",
        prod5Desc: "Intelligent virtual assistant that optimizes workflows and automates routine tasks.",
        prod5Feature1: "Natural language processing",
        prod5Feature2: "Task automation",
        prod5Feature3: "CRM integration",
        prod5Feature4: "Multi-language support",
        prod6Category: "E-Commerce",
        prod6Title: "E-Commerce Suite",
        prod6Desc: "Complete e-commerce platform with built-in marketing tools and sales analytics.",
        prod6Feature1: "Unlimited products",
        prod6Feature2: "Multiple payment methods",
        prod6Feature3: "SEO optimization",
        prod6Feature4: "Email marketing",
        perMonth: "/month",
        orderNow: "Order Now",
        comparisonTitle: "Plan Comparison",
        comparisonSubtitle: "Choose the plan that best fits your needs",
        tableFeature: "Feature",
        planStarter: "Starter",
        planProfessional: "Professional",
        planEnterprise: "Enterprise",
        tableUsers: "Number of Users",
        usersUpTo10: "Up to 10",
        usersUpTo50: "Up to 50",
        usersUnlimited: "Unlimited",
        tableStorage: "Storage",
        storageUnlimited: "Unlimited",
        tableApiAccess: "API Access",
        tableTechSupport: "Technical Support",
        tableAiFeatures: "AI Features",
        tableCustomization: "Customization",
        customizationLimited: "Limited",
        customizationFull: "Full",
        tableTraining: "Training",
        testimonialsTitle: "What Our Clients Say",
        testimonialsSubtitle: "Real reviews from satisfied customers",
        testimonial1Text: "Business Analytics Pro transformed the way we analyze our data. An incredibly powerful tool!",
        testimonial1Avatar: "IP",
        testimonial1Name: "Ivan Petrov",
        testimonial1Position: "CEO, TechStart Ltd.",
        testimonial2Text: "CloudSync Enterprise saved us hundreds of hours of work. The synchronization is flawless and security is top-notch.",
        testimonial2Avatar: "MD",
        testimonial2Name: "Maria Dimitrova",
        testimonial2Position: "CTO, Digital Solutions",
        testimonial3Text: "We've been using TeamWork Manager for 2 years now. Team productivity increased by 40%. Highly recommend!",
        testimonial3Avatar: "GG",
        testimonial3Name: "Georgi Georgiev",
        testimonial3Position: "Project Manager, CreativeHub",
        ctaStartTrial: "Start Free Trial",
        ctaContactUs: "Contact Us",
        
        // Contact page
        contactHeroTitle: "Get in Touch",
        contactHeroSubtitle: "We look forward to your questions and suggestions. Our team is at your disposal!",
        contactInfoTitle: "Contact Information",
        addressLabel: "Address",
        addressText: "123 Vitosha Blvd.<br>Sofia 1000, Bulgaria",
        emailLabel: "Email",
        emailGeneral: "General:",
        emailSupport: "Support:",
        phoneLabel: "Phone",
        phoneOffice: "Office:",
        phoneMobile: "Mobile:",
        hoursLabel: "Working Hours",
        hoursWeekdays: "Monday - Friday: 9:00 AM - 6:00 PM",
        hoursWeekend: "Saturday - Sunday: Closed",
        formTitle: "Send an Inquiry",
        formName: "Your Name *",
        formEmail: "Email Address *",
        formPhone: "Phone",
        formSubject: "Inquiry Subject",
        subjectGeneral: "General Information",
        subjectServices: "Services",
        subjectProducts: "Products",
        subjectSupport: "Technical Support",
        subjectPartnership: "Partnership",
        formMessage: "Your Message *",
        formSubmit: "Send Message",
        mapTitle: "Find Us",
        mapPlaceholder: "🗺️ Google Maps will load here",
        socialTitle: "Follow Us"
    },
    bg: {
        // Header
        logo: "Име на Компанията",
        home: "Начало",
        about: "За Нас",
        services: "Услуги",
        products: "Продукти",
        contact: "Контакти",
        
        // Index page - Hero
        heroTitle: "Добре дошли в Company Name",
        heroSubtitle: "Иновативни решения за успеха на вашия бизнес. Превръщаме идеите в реалност с най-съвременни технологии.",
        exploreServices: "Разгледайте Нашите Услуги",
        getInTouch: "Свържете се с нас",
        
        // Index page - Sections
        aboutTitle: "За Нас",
        aboutText: "Ние сме водеща технологична компания, посветена на предоставянето на иновативни решения, които стимулират растежа на бизнеса. С над 10 години опит и екип от 50+ специалисти помагаме на бизнеса да се трансформира чрез технологии.",
        learnMore: "Научете Повече",
        
        servicesTitle: "Нашите Услуги",
        servicesText: "Предлагаме цялостни технологични решения, съобразени с нуждите на вашия бизнес.",
        viewAllServices: "Вижте Всички Услуги →",
        
        productsTitle: "Нашите Продукти",
        productsText: "Иновативни софтуерни продукти, проектирани за бизнес върхови постижения.",
        prod1Preview: "AI-базирана платформа за анализ за решения, базирани на данни.",
        prod2Preview: "Сигурна облачна платформа за управление на корпоративни данни.",
        prod3Preview: "Система за управление на проекти с инструменти за сътрудничество.",
        viewAllProducts: "Вижте Всички Продукти →",
        
        // References Section
        referencesTitle: "Какво Казват Нашите Клиенти",
        referencesText: "Чуйте от бизнесите, на които помогнахме да успеят с нашите технологични решения.",
        testimonial1Text: "Работата с Company Name трансформира нашия бизнес. Тяхната уеб платформа увеличи продажбите ни със 150% в първата година.",
        testimonial1Name: "Иван Петров",
        testimonial1Position: "Изпълнителен директор, TechStart България",
        testimonial2Text: "Изключително обслужване и изключителни резултати. Мобилното приложение, което разработиха, надмина всичките ни очаквания.",
        testimonial2Name: "Мария Иванова",
        testimonial2Position: "Директор, Retail Solutions",
        testimonial3Text: "Професионален екип с дълбоки технически познания. Доставиха нашия проект за облачна миграция навреме и в рамките на бюджета.",
        testimonial3Name: "Георги Димитров",
        testimonial3Position: "IT Мениджър, Finance Corp",
        
        contactTitle: "Готови ли сте да започнете вашия проект?",
        contactText: "Свържете се с нашия екип, за да обсъдим как можем да помогнем за трансформирането на вашия бизнес с иновативни технологични решения.",
        contactButton: "Свържете се с нас сега",
        
        // Footer
        quickLinks: "Бързи Връзки",
        support: "Поддръжка",
        connect: "Свържете се",
        homeLink: "Начало",
        aboutUs: "За Нас",
        faq: "Често Задавани Въпроси",
        helpCenter: "Помощен Център",
        contactUs: "Свържете се с Нас",
        privacyPolicy: "Политика за Поверителност",
        facebook: "Facebook",
        twitter: "Twitter",
        linkedin: "LinkedIn",
        instagram: "Instagram",
        copyright: "Всички права запазени.",
        terms: "Условия за Ползване",
        
        // About page
        aboutHeroTitle: "За Нас",
        aboutHeroSubtitle: "Иновации, качество и отдаденост – това е нашата мисия",
        ourStoryTitle: "Нашата История",
        ourStoryP1: "Company Name е основана през 2010 година с визия да трансформира начина, по който бизнесът използва технологиите. Започнахме като малък екип от ентусиасти, обединени от обща страст към иновациите и качествените решения.",
        ourStoryP2: "През годините израснахме до водеща компания в областта на бизнес технологиите, обслужваща стотици клиенти в България и чужбина. Нашият успех се крие в посвещението към клиентите и непрекъснатото усъвършенстване.",
        ourStoryP3: "Днес сме горди с екип от над 50 професионалисти, модерни офиси и портфолио от успешно реализирани проекти в различни индустрии – от финанси и здравеопазване до търговия и производство.",
        achievementsTitle: "Нашите Постижения",
        projects: "Проекта",
        clients: "Клиенти",
        yearsExp: "Години Опит",
        specialists: "Специалисти",
        ourTeamTitle: "Нашият Екип",
        ceo: "Изпълнителен Директор",
        cto: "Технически Директор",
        devManager: "Мениджър Развойна",
        designDirector: "Дизайн Директор",
        ceoBio: "15 години опит в IT индустрията. Визионер с фокус върху иновациите.",
        ctoBio: "Експерт в софтуерна архитектура и управление на технологични проекти.",
        devManagerBio: "Passionate developer и лидер на екип от талантливи програмисти.",
        designDirectorBio: "Креативен ум с фокус върху user experience и визуална комуникация.",
        ourValuesTitle: "Нашите Ценности",
        qualityTitle: "Качество",
        qualityDesc: "Стремим се към най-високи стандарти във всеки проект и взаимодействие с клиентите.",
        innovationTitle: "Иновации",
        innovationDesc: "Непрекъснато търсим нови технологии и подходи за решаване на бизнес предизвикателства.",
        partnershipTitle: "Партньорство",
        partnershipDesc: "Изграждаме дългосрочни отношения, основани на доверие и взаимна полза.",
        commitmentTitle: "Ангажираност",
        commitmentDesc: "Отдадени сме на успеха на нашите клиенти и техния растеж.",
        
        // Services page
        servicesHeroTitle: "Нашите Услуги",
        servicesHeroSubtitle: "Цялостни решения, съобразени с нуждите на вашия бизнес. Предоставяме върхови постижения чрез иновации и експертни познания.",
        whatWeOffer: "Какво Предлагаме",
        bizConsultTitle: "Бизнес Консултации",
        bizConsultDesc: "Стратегическо планиране и консултантски услуги, за да помогнем на вашия бизнес да расте и успява на конкурентни пазари.",
        webDevTitle: "Уеб Разработка",
        webDevDesc: "Персонализирани уеб приложения и уебсайтове, създадени с модерни технологии, за да подобрят вашето дигитално присъствие.",
        mobileAppTitle: "Мобилни Приложения",
        mobileAppDesc: "Нативни и кроспла���формени мобилни приложения, проектирани да ангажират вашите клиенти на iOS и Android устройства.",
        uiUxTitle: "UI/UX Дизайн",
        uiUxDesc: "Потребителски ориентирани дизайн решения, които създават интуитивни и визуално привлекателни дигитални преживявания.",
        cloudTitle: "Облачни Решения",
        cloudDesc: "Мащабируема облачна инфраструктура и услуги за миграция, за модернизиране на вашите IT операции.",
        dataAnalyticsTitle: "Анализ на Данни",
        dataAnalyticsDesc: "Трансформирайте вашите данни в действащи прозрения с усъвършенствани инструменти за анализ и бизнес разузнаване.",
        cybersecurityTitle: "Киберсигурност",
        cybersecurityDesc: "Цялостни решения за сигурност, за да защитите вашия бизнес от киберзаплахи и уязвимости.",
        aiMlTitle: "AI & Машинно Обучение",
        aiMlDesc: "Използвайте изкуствен интелект и машинно обучение, за да автоматизирате процеси и да получите конкурентни предимства.",
        learnMore: "Научете Повече",
        whyChooseUs: "Защо Да Изберете Нас",
        provenExpertiseTitle: "🏆 Доказана Експертност",
        provenExpertiseDesc: "Над 10 години опит в доставката на успешни проекти в различни индустрии.",
        fastDeliveryTitle: "⚡ Бърза Доставка",
        fastDeliveryDesc: "Agile методологии осигуряват бърза разработка и внедряване без компромис с качеството.",
        qualityAssuranceTitle: "💎 Осигуряване на Качеството",
        qualityAssuranceDesc: "Строги процеси на тестване и контрол на качеството гарантират надеждни и безпроблемни решения.",
        dedicatedSupportTitle: "🤝 Отдадена Поддръжка",
        dedicatedSupportDesc: "24/7 клиентска поддръжка и поддръжка, за да поддържате вашите системи да работят гладко.",
        ctaTitle: "Готови Ли Сте Да Започнете?",
        ctaSubtitle: "Нека обсъдим как нашите услуги могат да помогнат за трансформирането на вашия бизнес. Свържете се с нас днес за безплатна консултация.",
        requestQuote: "Поискайте Оферта",
        
        // Products page
        productsHeroTitle: "Нашите Продукти",
        productsHeroSubtitle: "Иновативни решения, разработени с най-съвременни технологии за успеха на вашия бизнес",
        discoverOurRange: "Открийте Нашата Продуктова Гама",
        fromStartupsTo: "От малки стартъпи до големи корпорации - имаме перфектното решение за всеки бизнес",
        badgeNew: "Ново",
        badgePopular: "Популярен",
        badgeBestseller: "Бестселър",
        prod1Category: "Бизнес Аналитика",
        prod1Title: "Business Analytics Pro",
        prod1Desc: "Мощна платформа за бизнес анализ с AI-базирани прогнози и визуализация на данни в реално време.",
        prod1Feature1: "Интерактивни дашборди",
        prod1Feature2: "Прогнозен анализ с AI",
        prod1Feature3: "Експорт в Excel, PDF",
        prod1Feature4: "Интеграция с ERP системи",
        prod2Category: "Облачни Решения",
        prod2Title: "CloudSync Enterprise",
        prod2Desc: "Сигурна облачна платформа за съхранение, синхронизация и споделяне на корпоративни данни.",
        prod2Feature1: "Неограничено хранилище",
        prod2Feature2: "256-bit криптиране",
        prod2Feature3: "Автоматичен backup",
        prod2Feature4: "24/7 техническа поддръжка",
        prod3Category: "Управление на Проекти",
        prod3Title: "TeamWork Manager",
        prod3Desc: "Интуитивна система за управление на проекти и екипи с вградени инструменти за комуникация.",
        prod3Feature1: "Kanban и Gantt диаграми",
        prod3Feature2: "Видео конференции",
        prod3Feature3: "Проследяване на време",
        prod3Feature4: "Мобилно приложение",
        prod4Category: "Киберсигурност",
        prod4Title: "SecureGuard Pro",
        prod4Desc: "Комплексна защита срещу киберзаплахи с AI детекция на аномалии и автоматична защита.",
        prod4Feature1: "Защита в реално време",
        prod4Feature2: "Firewall и антивирус",
        prod4Feature3: "Мониторинг на трафик",
        prod4Feature4: "Автоматични актуализации",
        prod5Category: "Изкуствен Интелигент",
        prod5Title: "AI Assistant Plus",
        prod5Desc: "Интелигентен виртуален асистент, оптимизиращ работните процеси и автоматизиращ рутинни задачи.",
        prod5Feature1: "Обработка на естествен език",
        prod5Feature2: "Автоматизация на задачи",
        prod5Feature3: "Интеграция с CRM",
        prod5Feature4: "Многоезична поддръжка",
        prod6Category: "Електронна Търговия",
        prod6Title: "E-Commerce Suite",
        prod6Desc: "Пълна платформа за електронна търговия с вградени маркетинг инструменти и анализ на продажби.",
        prod6Feature1: "Неограничени продукти",
        prod6Feature2: "Множество платежни методи",
        prod6Feature3: "SEO оптимизация",
        prod6Feature4: "Email маркетинг",
        perMonth: "/месец",
        orderNow: "Поръчай",
        comparisonTitle: "Сравнение на Планове",
        comparisonSubtitle: "Изберете плана, който най-добре отговаря на вашите нужди",
        tableFeature: "Функционалност",
        planStarter: "Starter",
        planProfessional: "Professional",
        planEnterprise: "Enterprise",
        tableUsers: "Брой потребители",
        usersUpTo10: "До 10",
        usersUpTo50: "До 50",
        usersUnlimited: "Неограничен",
        tableStorage: "Хранилище",
        storageUnlimited: "Неограничено",
        tableApiAccess: "API достъп",
        tableTechSupport: "Техническа поддръжка",
        tableAiFeatures: "AI функции",
        tableCustomization: "Персонализация",
        customizationLimited: "Ограничена",
        customizationFull: "Пълна",
        tableTraining: "Обучение",
        testimonialsTitle: "Какво Казват Нашите Клиенти",
        testimonialsSubtitle: "Реални отзиви от доволни клиенти",
        testimonial1Text: "Business Analytics Pro трансформира начина, по който анализираме нашите данни. Невероятно мощен инструмент!",
        testimonial1Avatar: "ИП",
        testimonial1Name: "Иван Петров",
        testimonial1Position: "CEO, TechStart ООД",
        testimonial2Text: "CloudSync Enterprise ни спести стотици часове работа. Синхронизацията е безупречна и сигурността е на най-високо ниво.",
        testimonial2Avatar: "МД",
        testimonial2Name: "Мария Димитрова",
        testimonial2Position: "CTO, Digital Solutions",
        testimonial3Text: "Използваме TeamWork Manager вече 2 години. Продуктивността на екипа се повиши с 40%. Силно препоръчвам!",
        testimonial3Avatar: "ГГ",
        testimonial3Name: "Георги Георгиев",
        testimonial3Position: "Мениджър Проекти, CreativeHub",
        ctaStartTrial: "Започни безплатен тест",
        ctaContactUs: "Свържи се с нас",
        
        // Contact page
        contactHeroTitle: "Свържете се с нас",
        contactHeroSubtitle: "Очакваме вашите въпроси и предложения. Нашият екип е на разположение!",
        contactInfoTitle: "Информация за контакт",
        addressLabel: "Адрес",
        addressText: "бул. \"Витоша\" 123<br>София 1000, България",
        emailLabel: "Имейл",
        emailGeneral: "Основен:",
        emailSupport: "Поддръжка:",
        phoneLabel: "Телефон",
        phoneOffice: "Офис:",
        phoneMobile: "Мобилен:",
        hoursLabel: "Работно време",
        hoursWeekdays: "Понеделник - Петък: 9:00 - 18:00",
        hoursWeekend: "Събота - Неделя: Почивни дни",
        formTitle: "Изпратете запитване",
        formName: "Вашето име *",
        formEmail: "Имейл адрес *",
        formPhone: "Телефон",
        formSubject: "Тема на запитването",
        subjectGeneral: "Обща информация",
        subjectServices: "Услуги",
        subjectProducts: "Продукти",
        subjectSupport: "Техническа поддръжка",
        subjectPartnership: "Партньорство",
        formMessage: "Вашето съобщение *",
        formSubmit: "Изпрати съобщение",
        mapTitle: "Намерете ни",
        mapPlaceholder: "🗺️ Тук ще се зареди Google Maps",
        socialTitle: "Последвайте ни"
    }
};

// Get current language from localStorage or default to English
let currentLanguage = localStorage.getItem('language') || 'en';

// Function to translate page
function translatePage() {
    const elements = document.querySelectorAll('[data-translate]');
    
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLanguage][key]) {
            element.textContent = translations[currentLanguage][key];
        }
    });
    
    // Update HTML lang attribute
    document.documentElement.lang = currentLanguage === 'bg' ? 'bg' : 'en';
    
    // Update language button text
    const langBtn = document.getElementById('langToggle');
    if (langBtn) {
        langBtn.textContent = currentLanguage === 'en' ? 'BG' : 'EN';
        langBtn.title = currentLanguage === 'en' ? 'Switch to Bulgarian' : 'Превключи на английски';
    }
}

// Function to toggle language
function toggleLanguage() {
    currentLanguage = currentLanguage === 'en' ? 'bg' : 'en';
    localStorage.setItem('language', currentLanguage);
    translatePage();
}

// Initialize translation on page load
document.addEventListener('DOMContentLoaded', () => {
    translatePage();
    
    // Add event listener to language toggle button
    const langBtn = document.getElementById('langToggle');
    if (langBtn) {
        langBtn.addEventListener('click', toggleLanguage);
    }
});
